# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.0
_src_path: gh:radio-aktywne/template-devcontainer
accountname: radio-aktywne
description: Devcontainer for Flux manifests ☸️
devcontainername: flux
docs: true
docsurl: https://radio-aktywne.github.io/devcontainer-flux
imagename: devcontainers/flux
registry: true
releases: true
reponame: devcontainer-flux
repourl: https://github.com/radio-aktywne/devcontainer-flux
